blank_issues_enabled: false
contact_links:
  - name: farm-ng Community Support
    url: https://discourse.farm-ng.com/
    about: Please ask and answer questions here.
  - name: Documentation Requests/ Issues
    url: https://github.com/farm-ng/amiga-dev-kit/issues/new/choose
    about: Please report your documentation request or issues here.
