name: 🚀 Feature Request
description: Suggest an idea for this project
title: "[Feature Request]: "
labels: ["feature-request"]
assignees:
  - Hackerman342
projects:
  - farm-ng/Amiga-support-issues
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit your feature request!

  - type: textarea
    id: describe-feature
    attributes:
      label: Describe the feature you want
      description: A clear and concise description of the feature proposal.
    validations:
      required: true

  - type: textarea
    id: background-information
    attributes:
      label: Background Information
      description: A clear and concise description of what problem this feature will solve. Ex. I'm always frustrated when [...]. If this is related to another GitHub issue, please link here too.
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
